export default {
  react: ["ری‌اکت", "reactjs"],
  vue: ["ویو", "vuejs"],
  angular: ["انگولار", "angularjs"],
  gatsbyjs: ["گتسبی", "gatsby"],
  static: ["استاتیک"],
  nodejs: ["نود جی اس", "node", "نود"],
  nestjs: ["نست جی اس", "نست", "nest"],
  nextjs: ["نکست", "نکست جی اس", "next"],
  strapi: ["استرپی", "strapijs", "استرپی جی اس"],
  adonis: ["adonisjs", "ادانیس"],
  laravel: ["لاراول"],
  wordpress: ["وردپرس", "cms"],
  django: ["جنگو", "python", "پایتون"],
  flask: ["فلسک", "python", "پایتون"],
  docker: ["داکر"],
  ".net": ["dot net", "dotnet", "دات نت", "asp", "asp.net Core", "net core"],
  mysql: ["مای اس کیو ال"],
  mariadb: ["ماریا دی بی"],
  postgresql: ["پستگرس"],
  "sql server": ["اس کیو ال سرور"],
  mongodb: ["مونگو", "مونگو دی بی"],
  redis: ["ردیس"],
  pusher: ["پوشر", "وب سوکت", "web socket"],
  ghost: ["گست"],
  "rocket.chat": ["راکت چت", "rocket chat"],
  gitea: ["گیتی", "گیتیی"],
  metabase: ["متابیس"],
  chrome: ["کروم"],
  nextcloud: ["نکست کلود"],
  imgproxy: ["image proxy", "ایمیج پروکسی"],
  yii: [],
  prestashop: ["پرستاشاپ"],
  nginx: ["انجینیکس"],
  go: ["گو"],
  elastic: ["الستیک", "الاستیک"],
  kibana: ["کیبانا"],
  grafana: ["گرافانا"],
  mttermost: [],
  rabbitmq: [],
  arangodb: [],
  seq: [],
  celery: ["سلری"],
  php: ["پی اچ پی"],
  subdomain: ["زیر‌دامنه", "ساب‌دامنه", "ساب دامنه", "زیر دامنه"],
};
